#!/bin/sh -e

# Build a binary DEB package from a source package.

if [ -z "$1" ]; then
    echo "Usage: $0 <filename.dsc>" 1>&2
    exit 1
fi

. /etc/dbd/dbd.conf
# If a base root FS tarball is not created yet, create it
[ -f "$BASETGZ" ] || dbd-mktgz

# Do the chrooted build
sudo -n /usr/sbin/pbuilder \
    --build \
    --configfile /etc/dbd/dbd.conf \
    "$1"
