#!/bin/sh

# Remove DEB package(s) from an APT repository.
# This includes removing the files from the repository dirs
# and updating an index files of the repository (with PGP
# signing, if configured).

set -e

if [ -z "$1" ]; then
    echo "Usage: $0 <packagename>" 1>&2
    exit 1
fi

. /etc/dbd.conf

sudo -n /usr/bin/reprepro \
    --basedir "$REPREPRO_DIR" \
    remove "$DISTRIBUTION" \
    "$1"
