#!/bin/sh -e

# Login in a base root FS tarball.
# No changes will be saved after a logout.

. /etc/dbd/dbd.conf
# If the base root FS tarball is not created yet, create it
[ -f "$BASETGZ" ] || dbd-mktgz

# Unpack the base root FS tarball and chroot into it
sudo -n /usr/sbin/pbuilder \
    --login \
    --configfile /etc/dbd/dbd.conf
